CREATE TABLE "recurring_donation_payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"recurring_donation_id" uuid NOT NULL,
	"donation_id" uuid NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(3) NOT NULL,
	"payment_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"stripe_invoice_id" varchar(255),
	"stripe_payment_intent_id" varchar(255),
	"paystack_transaction_id" varchar(255),
	"billing_period_start" date NOT NULL,
	"billing_period_end" date NOT NULL,
	"scheduled_date" date NOT NULL,
	"processed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recurring_donations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"campaign_id" uuid NOT NULL,
	"donor_id" uuid NOT NULL,
	"chainer_id" uuid,
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(3) NOT NULL,
	"period" varchar(20) NOT NULL,
	"payment_method" varchar(50) NOT NULL,
	"stripe_subscription_id" varchar(255),
	"paystack_subscription_id" varchar(255),
	"stripe_customer_id" varchar(255),
	"paystack_customer_code" varchar(255),
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"next_billing_date" date NOT NULL,
	"last_billing_date" date,
	"billing_day" integer,
	"message" text,
	"is_anonymous" boolean DEFAULT false NOT NULL,
	"total_donations" integer DEFAULT 0 NOT NULL,
	"total_amount" numeric(10, 2) DEFAULT '0' NOT NULL,
	"failed_attempts" integer DEFAULT 0 NOT NULL,
	"last_failure_reason" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"cancelled_at" timestamp,
	"paused_at" timestamp
);
